#!/usr/bin/env bash
# iter17 — cross-arch train+eval orchestrator for {vjepa_2_1_vitg, vjepa_2_0_vitg}.
# RTX Pro 6000 96 GB. BOTH backbones: parallel (2× GPU) OR sequential (1× GPU). Or ONE backbone.
#
# Usage:
#   ./scripts/iter17_poc_2gpu.sh [--mode=SANITY|POC] [--BACKBONE=<name>] [--cache=1|2] [--gpus=1|2]
#     --mode=SANITY|POC   default POC. SANITY ≈ minutes (validate paths) · POC ≈ real 10k numbers.
#     --gpus=1|2          default 2. 2 = both backbones PARALLEL (one per GPU; ~21h wall, needs a
#                         2× GPU node) · 1 = both backbones SEQUENTIAL on GPU 0 (~42h wall, but a
#                         1× GPU node is cheaper/hr → lower TOTAL $). Ignored when --BACKBONE is set.
#     --BACKBONE=<name>   OPTIONAL. If set → run ONLY that backbone on 1× GPU (GPU 0), FULL eval
#                         (incl paired-Δ). If omitted → BOTH backbones (per --gpus); their eval
#                         defers the shared paired-Δ aggregate to §3 (run once over ALL encoders).
#     --cache=1|2         default 2. cache-policy forwarded to run_train + run_eval (both modes):
#                         1=keep/reuse (resume — skip already-computed) · 2=recompute-from-scratch
#                         (WIPE output dir + rebuild). Applies identically to SANITY and POC.
#     --min-free=<GB>     OPTIONAL override of the disk-preflight threshold. By default the script
#                         ABORTS before any GPU work if free disk < n_backbones×120G + 20G (per
#                         backbone ≈ 71G m09 ckpts + 45G probe_taxonomy heads). Use to bypass when
#                         you'll free space mid-run yourself.
#   (bare positional SANITY|POC still accepted for back-compat, e.g. `... SANITY`.)
#   examples:
#
#     # 1× GPU SEQUENTIAL — both backbones, cheaper node (~42h, ~$55 @ $1.3/hr)   ← preferred
#     bash scripts/iter17_poc_2gpu.sh --mode=POC --gpus=1 2>&1 | tee logs/iter17_1gpu_POC_both_$(date +%Y%m%d_%H%M%S).log
#
#     # 2× GPU PARALLEL — both backbones (~21h wall, ~$88 @ $4.2/hr)
#     bash scripts/iter17_poc_2gpu.sh --mode=POC --gpus=2 2>&1 | tee logs/iter17_2gpu_POC_both_$(date +%Y%m%d_%H%M%S).log
#
#     # 1× GPU — ONE backbone only (full eval); resume with --cache=1
#     bash scripts/iter17_poc_2gpu.sh --mode=POC --BACKBONE=vjepa_2_0_vitg 2>&1 | tee logs/iter17_1gpu_POC_vjepa_2_0_vitg_$(date +%Y%m%d_%H%M%S).log
#
# WHY SAFE ON A SHARED DISK (single node, one filesystem):
#   • training writes per-backbone dirs  outputs/<mode>/<BACKBONE>/m09*  → DISTINCT, no collision.
#   • shared data-derivation (train_pool/splits) is regenerated by EVERY arm at the SAME data path,
#     but writes are now ATOMIC (tmp+os.replace in clip_splits.py + probe_train_subset.py) →
#     concurrent identical-content rewrites are race-free.
#   • shared LABELS (action/taxonomy) are bootstrap-if-missing (NOT atomic) → in 2-lane mode lane-1
#     GATES on lane-0 having written them first (single-backbone mode needs no gate).
#   • 2-lane EVAL writes per-encoder dirs (distinct) and SKIPS the shared paired-Δ (4,7,9,9b,9c,12)
#     + labels (1) + plots (10,13); the combined paired-Δ + m13 run ONCE in §3 over ALL encoders.
#     1-backbone EVAL is self-contained → runs the FULL pipeline (SKIP_STAGES="") to validate it.
#
# Each lane = 7 train arms (pretrain_encoder FIRST — surgery inits from it) + eval.
# logs → logs/iter17_<mode>_<BACKBONE>_<ARM>_*.log  +  logs/iter17_<mode>_<BACKBONE>_eval_*.log
set -euo pipefail
cd "$(dirname "$0")/.."
source venv_walkindia/bin/activate
export PYTHONPATH=src

MODE="POC"
ONLY_BB=""
CACHE="2"                                          # cache-policy: 1=keep/reuse · 2=recompute-from-scratch (wipe)
GPUS_N="2"                                         # 2=both backbones parallel (2× GPU) · 1=sequential on GPU 0
for a in "$@"; do
    case "$a" in
        --mode=*)                  MODE="${a#*=}" ;;
        --backbone=*|--BACKBONE=*) ONLY_BB="${a#*=}" ;;
        --cache=*)                 CACHE="${a#*=}" ;;
        --gpus=*)                  GPUS_N="${a#*=}" ;;
        --min-free=*)              MIN_FREE_GB="${a#*=}" ;;
        SANITY|POC)                MODE="$a" ;;        # bare positional mode (back-compat)
        *) echo "FATAL: unknown arg '$a'. Usage: $0 [--mode=SANITY|POC] [--BACKBONE=<name>] [--cache=1|2] [--gpus=1|2] [--min-free=<GB>]"; exit 2 ;;
    esac
done
case "$MODE"   in SANITY|POC) ;; *) echo "FATAL: --mode must be SANITY or POC (got '$MODE')"; exit 2 ;; esac
case "$CACHE"  in 1|2) ;; *) echo "FATAL: --cache must be 1 (keep) or 2 (recompute) (got '$CACHE')"; exit 2 ;; esac
case "$GPUS_N" in 1|2) ;; *) echo "FATAL: --gpus must be 1 (sequential) or 2 (parallel) (got '$GPUS_N')"; exit 2 ;; esac
MODE_FLAG="--$MODE"
mtag="${MODE,,}"                                  # lowercase: sanity|poc — log tag + outputs/<mtag>/ path

BACKBONES=(vjepa_2_1_vitg vjepa_2_0_vitg)        # lane 0, lane 1 (2-GPU default)
GPUS=(0 1)
ARMS=(pretrain_encoder pretrain_2X_encoder surgery_3stage_DI_encoder surgery_noDI_encoder \
      pretrain_head surgery_3stage_DI_head surgery_noDI_head)
LABEL_A="outputs/${mtag}/probe_action/action_labels.json"
LABEL_T="outputs/${mtag}/probe_taxonomy/taxonomy_labels.json"
TS() { date +%Y%m%d_%H%M%S; }

# eval skip-set: single backbone = self-contained → FULL eval; 2-lane = defer shared aggregate to §3.
if [ -n "$ONLY_BB" ]; then
    case " ${BACKBONES[*]} " in *" $ONLY_BB "*) ;; \
        *) echo "FATAL: --BACKBONE must be one of: ${BACKBONES[*]} (got '$ONLY_BB')"; exit 2 ;; esac
    EVAL_SKIP=""
else
    EVAL_SKIP="1,4,7,9,9b,9c,12,13,10"
fi

# ── disk preflight — ABORT before any GPU work if free space < required ───────────────
# Per trainable backbone footprint ≈ 120G: ~71G m09 ckpts (4 enc×12G + 3 head×7.8G) +
# ~45G probe_taxonomy heads (16 dims × 356M × 8 encoders; head size ∝ embed_dim, NOT clips
# → same at SANITY & POC). n_backbones × 120G + 20G buffer. Override with --min-free=<GB>.
# Why FATAL-early: a 42h sequential POC that dies on a full disk at hour 30 wastes the whole run.
if [ -n "$ONLY_BB" ]; then N_BB=1; else N_BB=2; fi
REQ_GB=$(( N_BB * 120 + 20 ))
[ -n "${MIN_FREE_GB:-}" ] && REQ_GB="$MIN_FREE_GB"
FREE_GB=$(df -P outputs 2>/dev/null | awk 'NR==2 {printf "%d", $4/1024/1024}')
echo "  [disk-preflight] free=${FREE_GB}G · required≈${REQ_GB}G (${N_BB} backbone(s) × ~120G ckpts+taxonomy-heads + 20G buffer)"
if [ "${FREE_GB:-0}" -lt "$REQ_GB" ]; then
    echo "FATAL: insufficient disk — ${FREE_GB}G free < ${REQ_GB}G required for $MODE."
    echo "  free space first (reproducible scratch):  rm -rf outputs/sanity/"
    echo "  or override the check:                     MIN_FREE_GB=<GB> $0 $*"
    exit 3
fi

run_lane() {
    local gpu="$1" bb="$2" gate="$3"   # gate=1 → wait for shared labels before starting (2-lane lane-1)
    if [ "$gate" = 1 ]; then
        echo "[lane gpu$gpu $bb] waiting for shared labels (lane-0 prep) before start ..."
        while [ ! -f "$LABEL_A" ] || [ ! -f "$LABEL_T" ]; do sleep 5; done
        sleep 5   # let the atomic os.replace settle
        echo "[lane gpu$gpu $bb] labels present → starting"
    fi
    local arms_eval=""
    for a in frozen pretrain_encoder pretrain_2X_encoder pretrain_head \
             surgical_3stage_DI_encoder surgical_noDI_encoder surgical_3stage_DI_head surgical_noDI_head; do
        arms_eval="$arms_eval ${bb}_${a}"
    done
    local arm
    for arm in "${ARMS[@]}"; do
        echo "[lane gpu$gpu $bb] TRAIN $arm ($MODE)"
        CUDA_VISIBLE_DEVICES="$gpu" BACKBONE="$bb" CACHE_POLICY_ALL="$CACHE" \
            ./scripts/run_train.sh "$arm" "$MODE_FLAG" 2>&1 | tee "logs/iter17_${mtag}_${bb}_${arm}_$(TS).log"
        sleep 10
    done
    echo "[lane gpu$gpu $bb] EVAL ($MODE) ${arms_eval}"
    CUDA_VISIBLE_DEVICES="$gpu" ENCODERS="$arms_eval" SKIP_STAGES="$EVAL_SKIP" CACHE_POLICY_ALL="$CACHE" \
        ./scripts/run_eval.sh "$MODE_FLAG" 2>&1 | tee "logs/iter17_${mtag}_${bb}_eval_$(TS).log"
    echo "[lane gpu$gpu $bb] DONE"
}

if [ -n "$ONLY_BB" ]; then
    # ── single backbone on 1× GPU (GPU 0), serial, no gate, FULL eval ──
    echo "═══ iter17 $MODE · 1× GPU — single backbone $ONLY_BB @GPU0 (full eval) ═══"
    run_lane 0 "$ONLY_BB" 0
    echo "═══ $ONLY_BB $MODE DONE — inspect logs/iter17_${mtag}_${ONLY_BB}_*.log ═══"
    exit 0
fi

# ── both backbones — sequential (1× GPU) OR parallel (2× GPU), per --gpus ──
rc0=0; rc1=0
if [ "$GPUS_N" = 1 ]; then
    # 1× GPU SEQUENTIAL: backbone0 fully (train+eval) on GPU0, THEN backbone1 fully on GPU0.
    # No label-gate (only one lane at a time → no race). `|| rc=$?` so a failure in bb0 does
    # NOT abort bb1 (both have resume/checkpoint; CLAUDE.md "; not &&" queue rule).
    echo "═══ iter17 $MODE · 1× GPU SEQUENTIAL — ${BACKBONES[0]} → ${BACKBONES[1]} @GPU0 ═══"
    run_lane 0 "${BACKBONES[0]}" 0 || rc0=$?
    run_lane 0 "${BACKBONES[1]}" 0 || rc1=$?
else
    # 2× GPU PARALLEL: one backbone per GPU; lane-1 gates on lane-0's shared labels then runs.
    echo "═══ iter17 $MODE · 2× GPU PARALLEL — lane0=${BACKBONES[0]}@GPU${GPUS[0]} · lane1=${BACKBONES[1]}@GPU${GPUS[1]} ═══"
    run_lane "${GPUS[0]}" "${BACKBONES[0]}" 0 &   # lane 0 starts immediately (creates shared labels)
    PID0=$!
    run_lane "${GPUS[1]}" "${BACKBONES[1]}" 1 &   # lane 1 gated on labels, then parallel
    PID1=$!
    wait "$PID0" || rc0=$?
    wait "$PID1" || rc1=$?
fi
echo "═══ both backbones done ($MODE) · ${BACKBONES[0]} rc=$rc0 · ${BACKBONES[1]} rc=$rc1 ═══"
[ "$rc0" -eq 0 ] && [ "$rc1" -eq 0 ] || { echo "FATAL: a backbone failed — inspect logs/iter17_${mtag}_*; NOT running §3"; exit 1; }
echo "═══ both backbones PASSED ($MODE) — now run §3 (combined paired-Δ + m13 plots over ALL encoders) ═══"
echo "  see runbook §3 (CPU, ~15 min): m12a/b/c --stage paired_delta  +  m13_eval_plot.py"
